### ISSUE TITLE
Dosing methods bugged 

### ISSUE THREAD

**Issue by lorrandal** [psyfood/pyqmix#3] opened 2017-06-06 11:23 UTC
Dosign methods as `aspirate()` are bugged. After switching on the system, the first dosign mehtod that is called works as a calibration.
```python
    # TODO: First call after physical start is bugged (behaves like a calibration)       
    def aspirate(self, volume, flow_rate, blocking_wait=False):
        self.valve.switch_position(1)
#        self._dll.LCP_Aspirate(self._handle[0], volume, flow_rate) 
        self._call('LCP_Aspirate', self._handle[0], volume, flow_rate)       
        if blocking_wait:
            while self.is_pumping:
                time.sleep(0.0005)
```

**Comment by hoechenberger** [comment] 2018-10-04 08:27
Cannot reproduce this error anymore, closing.

**Closed by hoechenberger** 2018-10-04 08:27 UTC
